const fs=require('fs'),assert=require('node:assert/strict'),{JSDOM,VirtualConsole}=require('jsdom');
const html=fs.readFileSync(require('path').join(__dirname,'../app/src/main/assets/index.html'),'utf8');
async function boot(storage={}){const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const d=new JSDOM(html,{url:'https://local.test',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){for(const[k,v]of Object.entries(storage))w.localStorage.setItem(k,v);w.alert=()=>{};w.prompt=()=> '1234';w.confirm=()=>true;w.AndroidGame={recordError(){}};}});await new Promise(r=>d.window.addEventListener('load',r));assert.deepEqual(errors,[]);return d;}
function snap(w){return Object.fromEntries(Object.keys(w.localStorage).map(k=>[k,w.localStorage.getItem(k)]));}
(async()=>{let d=await boot(),w=d.window;w.prompt=(()=>{const p=['1234','1234',''];return()=>p.shift();})();w.document.getElementById('username-input').value='Wren';w.document.getElementById('answer-mode').value='hard';w.document.getElementById('math-operation').value='addition';w.login();assert.equal(w.eval('currentUser'),'Wren');w.eval('dollars=7;streak=2;saveData()');let saved=snap(w);w.close();
d=await boot(saved);w=d.window;assert.equal(w.eval('currentUser'),'Wren');assert.equal(w.eval('mode'),'hard');assert.equal(w.eval('currentOp'),'addition');assert.equal(w.eval('dollars'),7);assert.equal(w.eval('streak'),2);assert.equal(w.eval('db.profiles.length'),1);assert.equal(w.eval('parentAuthorized'),false);assert(w.document.getElementById('login-screen').classList.contains('hidden'));
w.logout();saved=snap(w);w.close();d=await boot(saved);w=d.window;assert.equal(w.eval('activeProfile'),null,'explicit switch must not auto-resume');w.close();
delete saved.mqPlayerSession;d=await boot(saved);w=d.window;assert.equal(w.eval('currentUser'),'Wren','upgrade with a single player auto-resumes');w.close();
saved.mqPlayerSession=JSON.stringify({name:'Missing',op:'division',mode:'hard'});d=await boot(saved);w=d.window;assert.equal(w.eval('activeProfile'),null);assert.equal(w.eval('db.profiles.length'),1,'never creates missing remembered player');w.close();
const db=JSON.parse(saved.robuxMathLocalV10);db.profiles.push({...JSON.parse(JSON.stringify(db.profiles[0])),name:'Sibling'});saved.robuxMathLocalV10=JSON.stringify(db);delete saved.mqPlayerSession;d=await boot(saved);w=d.window;assert.equal(w.eval('activeProfile'),null,'multiple profiles require selection until one is remembered');w.close();
console.log('PASS resume: restart restores player/mode/balances/streak, no duplicate profile or parent privilege; switch and stale selections remain safe');})().catch(e=>{console.error(e);process.exit(1)});
